version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=solar_panel
      - MYSQL_DATABASE=solarlinkdb
      - MYSQL_USER=user_solar_link
      - MYSQL_PASSWORD=user1
    ports:
      - 3306:3306
    volumes:
      - ./MySql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "solarlink", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  datagen:
    build: ./DataGen
    image: datagen
    container_name: datagen
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  web:
    build: ./demo
    image: solarlink
    container_name: solarlink
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 5001:8080
    environment:
    - SERVER_PORT=8080
    - SPRING_PROFILES_ACTIVE=prod
    - SPRING_APPLICATION_NAME=solarlink
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/solarlinkdb
    - SPRING_DATASOURCE_USERNAME=user_solar_link
    - SPRING_DATASOURCE_PASSWORD=user1
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
    - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQL8Dialect
    - SPRING_RABBITMQ_HOST=rabbitmq

  reactclient:
    build: ./frontend
    image: reactclient
    container_name: reactclient
    ports:
      - 3001:3000
    stdin_open: true
    depends_on:
      - web
    restart: unless-stopped
    